<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/02/28 08:20:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=symfonyband',
  'username' => 'symfonyband',
  'password' => 'symfonyband',
  'attributes' => 
  array (
    'default_table_charset' => 'utf8',
    'default_table_collate' => 'utf8_unicode_ci',
  ),
  'name' => 'doctrine',
)),);
